# Generated by Django 2.2.19 on 2021-04-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0114_auto_20210402_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_banned_from_voting_problem_points',
            field=models.BooleanField(default=False, help_text="User will not be able to vote on problems' points values.", verbose_name='banned from voting'),
        ),
    ]
