# Generated by Django 2.2.19 on 2021-04-19 01:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0115_contest_scoreboard_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_banned_from_voting_problem_points',
            field=models.BooleanField(default=False, help_text="User will not be able to vote on problems' points values.", verbose_name='banned from voting'),
        ),
        migrations.CreateModel(
            name='ProblemPointsVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(help_text='The amount of points you think this problem deserves.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='points')),
                ('note', models.TextField(blank=True, default=' ', help_text='Justification for problem points value.', max_length=2048, verbose_name='note')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_points_votes', to='judge.Problem')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_points_votes', to='judge.Profile')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
    ]
