# Generated by Django 2.2.19 on 2021-04-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0116_auto_20210405_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problempointsvote',
            name='note',
            field=models.TextField(blank=True, default=' ', help_text='Justification for problem points value.', max_length=2048, verbose_name='note'),
        ),
    ]
